name: Heroku Workflow

on:
  push:
    branches:
    - master


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

  build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Heroku
      uses: actions/heroku@1.0.0
      args: "container:login"
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
