name: Heroku Workflow

on:
  push:
    branches:
    - master


jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

  Deploy:
    needs: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v1
    - name: Login to Heroku
      id: login
      uses: actions/heroku@master
      with:
        args: "container:login"
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    - name: Push to Heroku
      uses: actions/heroku@master
      with:
        args: "container:push web -a \"$HEROKU_APP\""
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP: tsds-streamlit-example
    - name: Release to Heroku
      uses: actions/heroku@master
      with:
        args: "container:release web -a \"$HEROKU_APP\""
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP: tsds-streamlit-example